### ISSUE TITLE
little problems 🥶

### ISSUE THREAD

**Issue by AnGelXoG** [mumumusuc/termux-flutter#10]
![Screenshot_20231201_204508](https://github.com/mumumusuc/termux-flutter/assets/89430597/d3fd06c2-58f6-4a6e-90d7-a851bcc63433)
![Screenshot_20231201_204642](https://github.com/mumumusuc/termux-flutter/assets/89430597/e80a9526-e74c-488b-983d-5586d5813542)

**Comment by mumumusuc** [comment]
> cannot open display:

seems that env `DISPLAY` not set.

```
export DISPLAY=:0 && termux-x11 :0 &
flutter run 
```
