### ISSUE TITLE
Install command

### ISSUE THREAD

**Issue by Jobians** [mumumusuc/termux-flutter#12]
Please I don't understand your example install command

```
./install.py --engine /path/to/engine.tar.gz --dart-sdk /path/to/dart-sdk.tar.gz flutter
bash: ./install.py: No such file or directory
```

Can you please give full commands step by step

**Comment by Jobians** [comment]
Also you don't even add commands to install the dart and engine, please update.

**Comment by Jobians** [comment]
flutter create hello_world && cd hello_worldBuilding flutter tool...
/data/data/com.termux/files/home/flutter/bin/internal/shared.sh: line 24: /data/data/com.termux/files/home/flutter/bin/cache/dart-sdk/bin/dart: cannot execute: required file not found
Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left)

**Comment by Jobians** [comment]
~/termux-flutter $ ./install.py --engine /data/data/com.termux/files/home/engine.tar.gz --dart-sdk /data/data/com.termux/files/home/dart-sdk.tar.gz /data/data/com.termux/files/home/flutter    inconsisdent engine version:                      flutter:                                        a794cf2681c6c9fe7b260e0e84de96298dc9c18b                                                        engine.tar.gz:                                  22b600f240548c1cf6f5d3f9ae65a5c9e51bc443                                                      you may checkout the correct branch of flutter or run with option "--no-check" to disable version check.                                        ~/termux-flutter $

**Comment by Jobians** [comment]
~/hello $ termux-x11 :0 >/dev/null 2>&1 &
[2] 19538
[1]   Done                    export DISPLAY=:0 && termux-x11 :0
~/hello $ flutter run -d linux
Launching lib/main.dart on Linux in debug
mode...
Building Linux application...                   CMake Error at /data/data/com.termux/files/usr/share/cmake-3.27/Modules/FindPkgConfig.cmake:607 (message):
Building Linux application...                     A required package was not found
Building Linux application...                   Call Stack (most recent call first):
Building Linux application...                     /data/data/com.termux/files/usr/share/cmake-3.27/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
Building Linux application...                     flutter/CMakeLists.txt:25 (pkg_check_modules)
Building Linux application...                   
Building Linux application...                   
Building Linux application...                   
Exception: Unable to generate build files
[2]+  Done                    termux-x11 :0 > /dev/null 2>&1
~/hello $

**Comment by mumumusuc** [comment]
> Building Linux application... A required package was not found

make sure you have installed all dependencies listed in README
```
apt install gtk3 fontconfig xorgproto ninja cmake clang pkg-config
```

use `flutter run -v` to get the verbose error message

**Comment by Jobians** [comment]
Building Linux application...
(completed in 43.7s)
[   +1 ms] Exception: Build process failed
[   +7 ms] "flutter run" took 45,225ms.
[  +17 ms]
           #0      throwToolExit

(package:flutter_tools/src/base/common.dart:10:3
           )
           #1      RunCommand.runCommand

(package:flutter_tools/src/commands/run.dart:760
           :9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous
closure>

(package:flutter_tools/src/runner/flutter_comman
           d.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous
closure>

(package:flutter_tools/src/base/context.dart:150
           :19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand

(package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5

FlutterCommandRunner.runCommand.<anonymous
           closure>

(package:flutter_tools/src/runner/flutter_comman
           d_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous
closure>

(package:flutter_tools/src/base/context.dart:150
           :19)
           <asynchronous suspension>
           #7
FlutterCommandRunner.runCommand

(package:flutter_tools/src/runner/flutter_comman
           d_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous
closure>.<anonymous
           closure>

(package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous
closure>

(package:flutter_tools/src/base/context.dart:150
           :19)
           <asynchronous suspension>
           #10     main

(package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[  +29 ms] ensureAnalyticsSent: 0ms
[        ] Running 1 shutdown hook
[   +9 ms] Shutdown hooks complete
[        ] exiting with code 1
~/hello $

**Comment by Jobians** [comment]
Building Linux application...
(completed in 8.0s)
[  +68 ms] (hello:30647): Gtk-WARNING **:
12:26:58.170: cannot open display:
[  +22 ms] Error waiting for a debug connection:
The log
           reader stopped unexpectedly, or never
started.
[   +6 ms] Error launching application on Linux.
[+17354 ms] "flutter run" took 26,646ms.
[  +16 ms]
           #0      throwToolExit

(package:flutter_tools/src/base/common.dart:10:3
           )
           #1      RunCommand.runCommand

(package:flutter_tools/src/commands/run.dart:760
           :9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous
closure>

(package:flutter_tools/src/runner/flutter_comman
           d.dart:1297:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous
closure>

(package:flutter_tools/src/base/context.dart:150
           :19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand

(package:args/command_runner.dart:212:13)
           <asynchronous suspension>
           #5

FlutterCommandRunner.runCommand.<anonymous
           closure>

(package:flutter_tools/src/runner/flutter_comman
           d_runner.dart:339:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous
closure>

(package:flutter_tools/src/base/context.dart:150
           :19)
           <asynchronous suspension>
           #7
FlutterCommandRunner.runCommand

(package:flutter_tools/src/runner/flutter_comman
           d_runner.dart:285:5)
           <asynchronous suspension>
           #8      run.<anonymous
closure>.<anonymous
           closure>

(package:flutter_tools/runner.dart:115:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous
closure>

(package:flutter_tools/src/base/context.dart:150
           :19)
           <asynchronous suspension>
           #10     main

(package:flutter_tools/executable.dart:90:3)
           <asynchronous suspension>


[  +31 ms] ensureAnalyticsSent: 0ms
[        ] Running 1 shutdown hook
[  +10 ms] Shutdown hooks complete
[        ] exiting with code 1

**Comment by mumumusuc** [comment]
> +68 ms] (hello:30647): Gtk-WARNING **:
12:26:58.170: cannot open display:

env `DISPLAY` not set, please refer to README.
```
export DISPLAY=:0
# start x11 if it not running
termux-x11 :0 &
```

**Comment by mumumusuc** [comment]
> Brother I have read it and run that command already but error
> 
> ~ $ export DISPLAY=:0 && termux-x11 :0 & [1] 30382 [1] 2438 No command [1] found, did you mean: Command [ in package coreutils ~ $ "The XKEYBOARD keymap compiler (xkbcomp) reports:" "> "Warning: Could not resolve keysym XF86CameraAccessEnable "> "Warning: Could not resolve keysym XF86CameraAccessDisable "> "Warning: Could not resolve keysym XF86CameraAccessToggle "> "Warning: Could not resolve keysym XF86NextElement "> "Warning: Could not resolve keysym XF86PreviousElement "> "Warning: Could not resolve keysym XF86AutopilotEngageToggle "> "Warning: Could not resolve keysym XF86MarkWaypoint "> "Warning: Could not resolve keysym XF86Sos "> "Warning: Could not resolve keysym XF86NavChart "> "Warning: Could not resolve keysym XF86FishingChart "> "Warning: Could not resolve keysym XF86SingleRangeRadar "> "Warning: Could not resolve keysym XF86DualRangeRadar "> "Warning: Could not resolve keysym XF86RadarOverlay "> "Warning: Could not resolve keysym XF86TraditionalSonar "> "Warning: Could not resolve keysym XF86ClearvuSonar "> "Warning: Could not resolve keysym XF86SidevuSonar "> "Warning: Could not resolve keysym XF86NavInfo "Errors from xkbcomp are not fatal to the X server" ~ $

it's not error but latest `termux-x11`'s warning, hide it by running `termux-x11 :0 > /dev/null 2>&1 &`

**Comment by Jobians** [comment]
Brother it works now but I can't find the phone preview


~/hello $ flutter run
Launching lib/main.dart on Linux in debug
mode...
Building Linux application...                   

(hello:5926): Gdk-CRITICAL **: 12:53:28.517: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
Syncing files to device Linux...                                   126ms

Flutter run key commands.
r Hot reload. 🔥🔥🔥
R Hot restart.
h List all available interactive commands.
d Detach (terminate "flutter run" but leave
application running).
c Clear the screen
q Quit (terminate the application on the
device).

A Dart VM Service on Linux is available at:
http://127.0.0.1:40013/lTKYfjHfhYA=/
The Flutter DevTools debugger and profiler on
Linux is available at:
http://127.0.0.1:9100?uri=http://127.0.0.1:40013
/lTKYfjHfhYA=/
Performing hot reload...                        
Reloaded 0 libraries in 329ms (compile: 30 ms,
reload: 0 ms, reassemble: 242 ms).
Performing hot restart...                       
Restarted application in 709ms.

**Comment by Jobians** [comment]
Thanks brother for your time I appreciate.

It works now and then preview is showing in the Texmux:X11 app.

Thanks ❤️❤️
