### ISSUE TITLE
Important request

### ISSUE THREAD

**Issue by L4R-777** [mumumusuc/termux-flutter#16]
Have too much errors in step or may be am wrong at something, kindly make a documentation on complete setup from scratch. It worth giving the documentation on setup for future flutter developers. Thanking you

**Comment by mumumusuc** [comment]
what is the error message?

**Comment by L4R-777** [comment]
https://docs.google.com/document/d/1jOGrs3S3VhLp8-_d6LmgCfIKvu4wApV_0FfCYxU7nYI/edit?usp=drivesdk




Here is the output when running flutter build Linux


And can u please make doc of how to setup for Apk building(setup SDK, path)?

**Comment by mumumusuc** [comment]
`dart-sdk` is broken, remove `<flutter-path>/bin/cache/dart-sdk` then run the install script again.

> And can u please make doc of how to setup for Apk building(setup SDK, path)?

As [README](https://github.com/mumumusuc/termux-flutter#flavors) says, download [android-sdk](https://github.com/mumumusuc/termux-android-sdk/releases/tag/30.0.3) and follow the instruction in release page.

**Comment by L4R-777** [comment]
Can u please send me your telegram username ?

**Comment by mumumusuc** [comment]
> I installed dart from official termux cli, and removed dart from flutter/bin/dart, still error arises

flutter doesn't use user's `dart-sdk`.

run `flutter doctor -v` and paste the output
run `flutter clean` before `flutter run`

**Comment by L4R-777** [comment]
![Screenshot_2023-12-30-02-50-04-31_84d3000e3f4017145260f7618db1d683](https://github.com/mumumusuc/termux-flutter/assets/101415772/1d2f4f02-af1d-4a42-b30a-79ce9f5986b8)



I tried from scratch , it says some kinda Java versioning error

**Comment by mumumusuc** [comment]
>I tried from scratch , it says some kinda Java versioning error

That's not a problem, because `flutter` cannot parse version string like `17-internal`, it only accepts `17.xx.yy`.
