### ISSUE TITLE
Error when running the project

### ISSUE THREAD

**Issue by fuji-184** [mumumusuc/termux-flutter#18]
![Uploading XRecorder_09012024_045857.jpg…]()

flutter run
Launching lib/main.dart on Linux in debug mode...
Building Linux application...                     CMake Error at cmake_install.cmake:66 (file):
Building Linux application...                       file cannot create directory: /usr/local.  Maybe need administrative
Building Linux application...                       privileges.
Building Linux application...                     
Building Linux application...                     
Building Linux application...                     
Exception: Build process failed

**Comment by mumumusuc** [comment]
please provide more detailed message with `flutter run -v`
