### ISSUE TITLE
Cant install flutter.deb

### ISSUE THREAD

**Issue by popodepo123** [mumumusuc/termux-flutter#25]
I am very new to termux and linux environment. i followed the instructions, you said, but i does not let me install flutter.deb, can you teach me a step by step process for this?

**Comment by AnGelXoG** [comment]
> Soy muy nuevo en el entorno termux y linux. Seguí las instrucciones, dijiste, pero no me deja instalar flutter.deb, ¿puedes enseñarme un proceso paso a paso para esto?

![Screenshot_2024-03-18-16-00-26-45_84d3000e3f4017145260f7618db1d683](https://github.com/mumumusuc/termux-flutter/assets/89430597/0c018d1e-5865-4276-ad8d-481ed09024e0)

I hope this helps you!!

 In the end it was only necessary to install it that way, if it doesn't install anyway, then verify that you have installed all the dependencies.

**Comment by popodepo123** [comment]
thank you ~ I was able to install it now on termux
