### ISSUE TITLE
[ERROR] Error syncing engine source 

### ISSUE THREAD

**Issue by susandahal** [mumumusuc/termux-flutter#4]
![Screenshot_2023-10-12-13-14-59-096_com termux](https://github.com/mumumusuc/termux-flutter/assets/37948853/038976dd-b1ed-4d64-92e4-f8a80beca8ba)
![Screenshot_2023-10-12-13-14-27-503_com termux](https://github.com/mumumusuc/termux-flutter/assets/37948853/cdc70336-ce44-4f6b-8ad9-606d05abbda6)

**Comment by mumumusuc** [comment]
Network issue

**Comment by susandahal** [comment]
![Screenshot_2023-10-12-15-02-37-221_com android chrome](https://github.com/mumumusuc/termux-flutter/assets/37948853/f3515d84-cd7c-4703-8ae1-260c5fd041f8)

Internet seems fine. Everything else works..

**Comment by mumumusuc** [comment]
Try `DEPOT_TOOLS_UPDATE=0 gclient sync -v`

**Comment by susandahal** [comment]
![Screenshot_2023-10-12-15-31-31-232_com termux](https://github.com/mumumusuc/termux-flutter/assets/37948853/4406c748-6839-47fe-afaf-ef73c82b7275)

Using the same command. This is my .gclient file

**Comment by mumumusuc** [comment]
Try 
```
curl https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion -X post -d '{"package":"dart/dart-sdk/linux-arm64","version":"version:3.2.0-150.0.dev"}' --header "Content-Type: application/json"
# output
dart/dart-sdk/linux-arm64@8dd579640814cabaf3b7d6cd02eeb5a36cb8c2573646f78f10c0a537272a57d4?user:dart-internal-sdk@dart-ci-internal.iam.gserviceaccount.com"
```

**Comment by susandahal** [comment]
> Try
> 
> ```
> curl https://chrome-infra-packages.appspot.com/prpc/cipd.Repository/ResolveVersion -X post -d '{"package":"dart/dart-sdk/linux-arm64","version":"version:3.2.0-150.0.dev"}' --header "Content-Type: application/json" -v
> # output
> ...verbose...
> dart/dart-sdk/linux-arm64@8dd579640814cabaf3b7d6cd02eeb5a36cb8c2573646f78f10c0a537272a57d4?user:dart-internal-sdk@dart-ci-internal.iam.gserviceaccount.com"
> ```

This whole command?

![Screenshot_2023-10-12-16-04-05-367_com termux](https://github.com/mumumusuc/termux-flutter/assets/37948853/88b9ffe1-b8ff-4b94-9050-6eefda4111a3)

![Screenshot_2023-10-12-16-03-55-051_com termux](https://github.com/mumumusuc/termux-flutter/assets/37948853/c87a24a8-cfd2-4cfd-8ae6-8e1c02cb5ac9)

**Comment by mumumusuc** [comment]
> This whole command?

No, just the `curl` line.

I found the solution [here](https://github.com/termux/termux-app/issues/698#issuecomment-416908730). 

> `export https_proxy=http://localhost:1080` (not https) is the key

I am using proxy by default, so I wouldn't run into this problem.

**Comment by susandahal** [comment]
Thank you!!
