### ISSUE TITLE
Error when install

### ISSUE THREAD

**Issue by jongbatax** [mumumusuc/termux-flutter#5]
hello, i got error when install

./termux-flutter/install.py --engine engine.tar.gz --dart-sdk dart-sdk.tar.gz flutter           Traceback (most recent call last):
  File "/data/data/com.termux/files/home/./termux-flutter/install.py", line 134, in <module>
    sys.exit(main(sys.argv))                                  ^^^^^^^^^^^^^^                        File "/data/data/com.termux/files/home/./termux-flutter/install.py", line 127, in main              assert tarfile.is_tarfile(dart)
           ^^^^^^^^^^^^^^^^^^^^^^^^                File "/data/data/com.termux/files/usr/lib/python3.11/tarfile.py", line 2791, in is_tarfile
    t = open(name)                                       ^^^^^^^^^^                                 File "/data/data/com.termux/files/usr/lib/python3.11/tarfile.py", line 1804, in open
    return func(name, "r", fileobj, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/tarfile.py", line 1870, in gzopen
    fileobj = GzipFile(name, mode + "b", compresslevel, fileobj)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/gzip.py", line 174, in __init__
    fileobj = self.myfileobj = builtins.open(filename, mode or 'rb')
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/data/data/com.termux/files/home/flutter/bin/cache/artifacts/engine/dart-sdk.tar.gz'

**Comment by mumumusuc** [comment]
does `dart-sdk.tar.gz` exist in your current path?

**Comment by jongbatax** [comment]
![Uploading capture-2023-10-24-13-58-45.jpg…]()

this my termux files

**Comment by jongbatax** [comment]
![Uploading capture-2023-10-24-13-58-45.jpg…]()

this my termux files

**Comment by mumumusuc** [comment]
[`install.py`](https://github.com/mumumusuc/termux-flutter/blob/main/install.py) is updated, thanks for your feedback.
