### ISSUE TITLE
I can't install engines

~ $ ./install.py --engine $HOME/storage/shared/Download/engine.tar.gz --dart-sdk $HOME/storage/shared/Download/dart-sdk.tar.gz flutter bash: ./install.py: No such file or directory
~ $

I ran the above command on my termux and got an error ..

Is there anything that I am not doing right?
Thanks

### ISSUE THREAD

**Issue by bryght001** [mumumusuc/termux-flutter#8]
~ $ ./install.py --engine $HOME/storage/shared/Download/engine.tar.gz --dart-sdk $HOME/storage/shared/Download/dart-sdk.tar.gz flutter                                          bash: ./install.py: No such file or directory
~ $

I ran the above command on my termux and got an error ..

Is there anything that I am not doing right?
Thanks

**Comment by mumumusuc** [comment]
1. clone this repo or just download the [`install.py`](https://github.com/mumumusuc/termux-flutter/blob/main/install.py)
2. `./install.py` means `path/to/install.py`

**Comment by bryght001** [comment]
Thanks
