### ISSUE TITLE
Building flutter tool... /data/data/com.termux/files/home/termux-flutter/flutter/bin/internal/shared.sh: line 24: /data/data/com.termux/files/home/termux-flutter/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file: Exec format error Error: Unable to 'pub upgrade' flutter tool. Retrying in five seconds... (9 tries left) /data/data/com.termux/files/home/termux-flutter/flutter/bin/internal/shared.sh: line 24: /data/data/com.termux/files/home/termux-flutter/flutter/bin/cache/dart-sdk/bin/dart: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by bryght001** [mumumusuc/termux-flutter#9]
Please I keep getting this error what can I do

**Comment by mumumusuc** [comment]
please run 
```
apt install file
file /data/data/com.termux/files/home/termux-flutter/flutter/bin/cache/dart-sdk/bin/dart
```
then tell me the output.

It seems that aarch64 binary is not executable on your device if you have patched flutter correctly.

**Comment by bryght001** [comment]
file /data/data/com.termux/files/home/termux-flutter/flutter/bin/cache/dart-sdk/bin/dart
/data/data/com.termux/files/home/termux-flutter/flutter/bin/cache/dart-sdk/bin/dart: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, stripped

**Comment by mumumusuc** [comment]
> file /data/data/com.termux/files/home/termux-flutter/flutter/bin/cache/dart-sdk/bin/dart /data/data/com.termux/files/home/termux-flutter/flutter/bin/cache/dart-sdk/bin/dart: ELF 64-bit LSB pie executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, stripped

It is not the correct dart-sdk, have you patched flutter by running `install.py -d path/to/dart-sdk.tar.gz path/to/flutter`?

**Comment by bryght001** [comment]
./install.py --engine $HOME/engine.tar.gz --dart-sdk $HOME/dart-sdk.tar.gz flutter

This is what I used

**Comment by bryght001** [comment]
According to the readme.md file

**Comment by mumumusuc** [comment]
Remove `$HOME/termux-flutter/flutter/bin/cache/dart-sdk` and run the command again.

Error message says you are using the GNU's dart instead of the patched one, this [video tutorial](https://github.com/mumumusuc/termux-flutter/issues/7#issuecomment-1790704873) may be helpful(`set -p PATH ...` means `export PATH=...` in bash).
